import * as React from "react";
import { Truck, ToyBrick, Settings, HelpCircle, Menu, LayoutDashboard } from "lucide-react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { format } from "date-fns";
import { de } from "date-fns/locale";
import { Link } from "react-router-dom";
import logo from "@/assets/easybill-logo.svg";
import logoPlus from "@/assets/easybill-logo+.svg";
import { Bar, BarChart, CartesianGrid, XAxis, YAxis, Tooltip } from "recharts";
import { ChartContainer, ChartTooltipContent } from "@/components/ui/chart";
import { Card, CardHeader, CardContent } from "@/components/ui/card";

// Define the data type
type Order = {
  nr: number | string;
  kaufdatum: string;
  bestellnummer: string;
  info: string;
  kundeAdresse: string;
  email: string;
  telefonnummer: string;
  artikelanzahl: number;
  gesamtNetto: number;
  mwstSatz: number;
  gesamtBrutto: number;
  bezahltAm: string | null;
  statusRechnungsversand: "versendet" | "ausstehend" | "fehler";
  versandland: string;
  versanddienstleister: string;
  versandverpackung: string;
  versandprofil?: string;
  versandtGemeldet: string | null;
  statusVersanddokumente: "erstellt" | "ausstehend" | "fehler";
  versanddatum: string | null;
  versandBrutto: number;
  versandNetto: number;
  importdatum: string;
  importquelle: string;
  type: string;
};

// Sample data
const orders: Order[] = [
  {
    nr: 14,
    kaufdatum: "2025-11-01",
    bestellnummer: "7293846150",
    info: "Eilauftrag",
    kundeAdresse: "Max Müller, Hauptstr. 12, 10115 Berlin",
    email: "max.mueller@example.com",
    telefonnummer: "+49 30 12345678",
    artikelanzahl: 3,
    gesamtNetto: 84.03,
    mwstSatz: 19,
    gesamtBrutto: 100.00,
    bezahltAm: "2025-11-02",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DHL",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-11-02",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-11-03",
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-11-01",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: "14-0",
    kaufdatum: "2025-11-02",
    bestellnummer: "1847293651",
    info: "",
    kundeAdresse: "Anna Schmidt, Berliner Str. 45, 20095 Hamburg",
    email: "anna.schmidt@example.com",
    telefonnummer: "+49 40 23456789",
    artikelanzahl: 1,
    gesamtNetto: 42.02,
    mwstSatz: 19,
    gesamtBrutto: 50.00,
    bezahltAm: "2025-11-02",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "Hermes",
    versandverpackung: "Karton S",
    versandtGemeldet: "2025-11-03",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-11-04",
    versandBrutto: 4.99,
    versandNetto: 4.19,
    importdatum: "2025-11-02",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: 15,
    kaufdatum: "2025-11-05",
    bestellnummer: "3958274612",
    info: "Geschenkverpackung",
    kundeAdresse: "Peter Weber, Marktplatz 8, 80331 München",
    email: "peter.weber@example.com",
    telefonnummer: "+49 89 34567890",
    artikelanzahl: 5,
    gesamtNetto: 210.08,
    mwstSatz: 19,
    gesamtBrutto: 250.00,
    bezahltAm: null,
    statusRechnungsversand: "ausstehend",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DHL",
    versandverpackung: "Karton L",
    versandtGemeldet: null,
    statusVersanddokumente: "ausstehend",
    versanddatum: null,
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-11-05",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 16,
    kaufdatum: "2025-11-08",
    bestellnummer: "8472936150",
    info: "",
    kundeAdresse: "Sophie Fischer, Rheinstr. 22, 50667 Köln",
    email: "sophie.fischer@example.com",
    telefonnummer: "+49 221 45678901",
    artikelanzahl: 2,
    gesamtNetto: 126.05,
    mwstSatz: 19,
    gesamtBrutto: 150.00,
    bezahltAm: "2025-11-09",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DPD",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-11-09",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-11-10",
    versandBrutto: 5.49,
    versandNetto: 4.61,
    importdatum: "2025-11-08",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: "16-0",
    kaufdatum: "2025-11-10",
    bestellnummer: "6193847251",
    info: "Retourenfall",
    kundeAdresse: "Thomas Bauer, Schillerstr. 15, 60313 Frankfurt",
    email: "thomas.bauer@example.com",
    telefonnummer: "+49 69 56789012",
    artikelanzahl: 4,
    gesamtNetto: 336.13,
    mwstSatz: 19,
    gesamtBrutto: 400.00,
    bezahltAm: "2025-11-10",
    statusRechnungsversand: "fehler",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "UPS",
    versandverpackung: "Karton XL",
    versandtGemeldet: null,
    statusVersanddokumente: "fehler",
    versanddatum: null,
    versandBrutto: 8.99,
    versandNetto: 7.55,
    importdatum: "2025-11-10",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  // August Sendungen
  {
    nr: "18-0",
    kaufdatum: "2025-08-05",
    bestellnummer: "3847562910",
    info: "",
    kundeAdresse: "Michael Klein, Hauptstr. 7, 70173 Stuttgart",
    email: "michael.klein@example.com",
    telefonnummer: "+49 711 12345678",
    artikelanzahl: 2,
    gesamtNetto: 105.04,
    mwstSatz: 19,
    gesamtBrutto: 125.00,
    bezahltAm: "2025-08-05",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-08-06",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-08-07",
    versandBrutto: 5.49,
    versandNetto: 4.61,
    importdatum: "2025-08-05",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "19-0",
    kaufdatum: "2025-08-12",
    bestellnummer: "4756293841",
    info: "Express",
    kundeAdresse: "Sarah Hoffmann, Bahnhofstr. 23, 20095 Hamburg",
    email: "sarah.hoffmann@example.com",
    telefonnummer: "+49 40 23456789",
    artikelanzahl: 3,
    gesamtNetto: 168.07,
    mwstSatz: 19,
    gesamtBrutto: 200.00,
    bezahltAm: "2025-08-12",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton L",
    versandtGemeldet: "2025-08-13",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-08-14",
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-08-12",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "20-0",
    kaufdatum: "2025-08-18",
    bestellnummer: "5629384751",
    info: "",
    kundeAdresse: "Julia Becker, Maximilianstr. 15, 80539 München",
    email: "julia.becker@example.com",
    telefonnummer: "+49 89 34567890",
    artikelanzahl: 1,
    gesamtNetto: 42.02,
    mwstSatz: 19,
    gesamtBrutto: 50.00,
    bezahltAm: "2025-08-18",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "Hermes",
    versandverpackung: "Karton S",
    versandtGemeldet: "2025-08-19",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-08-20",
    versandBrutto: 4.99,
    versandNetto: 4.19,
    importdatum: "2025-08-18",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "21-0",
    kaufdatum: "2025-08-22",
    bestellnummer: "6293847562",
    info: "Geschenkverpackung",
    kundeAdresse: "Daniel Schulz, Hohe Str. 45, 50667 Köln",
    email: "daniel.schulz@example.com",
    telefonnummer: "+49 221 45678901",
    artikelanzahl: 4,
    gesamtNetto: 294.12,
    mwstSatz: 19,
    gesamtBrutto: 350.00,
    bezahltAm: "2025-08-22",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton XL",
    versandtGemeldet: "2025-08-23",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-08-24",
    versandBrutto: 7.99,
    versandNetto: 6.71,
    importdatum: "2025-08-22",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "22-0",
    kaufdatum: "2025-08-28",
    bestellnummer: "7384756293",
    info: "",
    kundeAdresse: "Nicole Wagner, Zeil 67, 60313 Frankfurt",
    email: "nicole.wagner@example.com",
    telefonnummer: "+49 69 56789012",
    artikelanzahl: 2,
    gesamtNetto: 126.05,
    mwstSatz: 19,
    gesamtBrutto: 150.00,
    bezahltAm: "2025-08-28",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "UPS",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-08-29",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-08-30",
    versandBrutto: 5.49,
    versandNetto: 4.61,
    importdatum: "2025-08-28",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  // September Sendungen
  {
    nr: "23-0",
    kaufdatum: "2025-09-03",
    bestellnummer: "8475629384",
    info: "Eilauftrag",
    kundeAdresse: "Robert Koch, Königsallee 12, 40212 Düsseldorf",
    email: "robert.koch@example.com",
    telefonnummer: "+49 211 67890123",
    artikelanzahl: 5,
    gesamtNetto: 210.08,
    mwstSatz: 19,
    gesamtBrutto: 250.00,
    bezahltAm: "2025-09-03",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton L",
    versandtGemeldet: "2025-09-04",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-09-05",
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-09-03",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "24-0",
    kaufdatum: "2025-09-09",
    bestellnummer: "9562938475",
    info: "",
    kundeAdresse: "Laura Meyer, Schillerstr. 8, 70173 Stuttgart",
    email: "laura.meyer@example.com",
    telefonnummer: "+49 711 23456789",
    artikelanzahl: 1,
    gesamtNetto: 84.03,
    mwstSatz: 19,
    gesamtBrutto: 100.00,
    bezahltAm: "2025-09-09",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "Hermes",
    versandverpackung: "Karton S",
    versandtGemeldet: "2025-09-10",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-09-11",
    versandBrutto: 4.99,
    versandNetto: 4.19,
    importdatum: "2025-09-09",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "25-0",
    kaufdatum: "2025-09-15",
    bestellnummer: "1629384756",
    info: "Retourenfall",
    kundeAdresse: "Markus Fischer, Hauptstr. 33, 20095 Hamburg",
    email: "markus.fischer@example.com",
    telefonnummer: "+49 40 34567890",
    artikelanzahl: 3,
    gesamtNetto: 168.07,
    mwstSatz: 19,
    gesamtBrutto: 200.00,
    bezahltAm: "2025-09-15",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-09-16",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-09-17",
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-09-15",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "26-0",
    kaufdatum: "2025-09-21",
    bestellnummer: "2738475629",
    info: "",
    kundeAdresse: "Stephanie Wolf, Bahnhofstr. 56, 80331 München",
    email: "stephanie.wolf@example.com",
    telefonnummer: "+49 89 45678901",
    artikelanzahl: 4,
    gesamtNetto: 252.10,
    mwstSatz: 19,
    gesamtBrutto: 300.00,
    bezahltAm: "2025-09-21",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton XL",
    versandtGemeldet: "2025-09-22",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-09-23",
    versandBrutto: 7.99,
    versandNetto: 6.71,
    importdatum: "2025-09-21",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "27-0",
    kaufdatum: "2025-09-27",
    bestellnummer: "3847562938",
    info: "Express",
    kundeAdresse: "Christian Bauer, Rheinstr. 89, 50667 Köln",
    email: "christian.bauer@example.com",
    telefonnummer: "+49 221 56789012",
    artikelanzahl: 2,
    gesamtNetto: 105.04,
    mwstSatz: 19,
    gesamtBrutto: 125.00,
    bezahltAm: "2025-09-27",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "UPS",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-09-28",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-09-29",
    versandBrutto: 5.49,
    versandNetto: 4.61,
    importdatum: "2025-09-27",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  // October Sendungen
  {
    nr: "28-0",
    kaufdatum: "2025-10-02",
    bestellnummer: "4756293847",
    info: "",
    kundeAdresse: "Melanie Schmidt, Maximilianstr. 34, 60313 Frankfurt",
    email: "melanie.schmidt@example.com",
    telefonnummer: "+49 69 67890123",
    artikelanzahl: 1,
    gesamtNetto: 42.02,
    mwstSatz: 19,
    gesamtBrutto: 50.00,
    bezahltAm: "2025-10-02",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "Hermes",
    versandverpackung: "Karton S",
    versandtGemeldet: "2025-10-03",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-10-04",
    versandBrutto: 4.99,
    versandNetto: 4.19,
    importdatum: "2025-10-02",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "29-0",
    kaufdatum: "2025-10-08",
    bestellnummer: "5629384756",
    info: "Geschenkverpackung",
    kundeAdresse: "Alexander Klein, Zeil 12, 40212 Düsseldorf",
    email: "alexander.klein@example.com",
    telefonnummer: "+49 211 78901234",
    artikelanzahl: 5,
    gesamtNetto: 294.12,
    mwstSatz: 19,
    gesamtBrutto: 350.00,
    bezahltAm: "2025-10-08",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton L",
    versandtGemeldet: "2025-10-09",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-10-10",
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-10-08",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "30-0",
    kaufdatum: "2025-10-14",
    bestellnummer: "6293847562",
    info: "",
    kundeAdresse: "Sabine Hoffmann, Schillerstr. 45, 70173 Stuttgart",
    email: "sabine.hoffmann@example.com",
    telefonnummer: "+49 711 34567890",
    artikelanzahl: 3,
    gesamtNetto: 168.07,
    mwstSatz: 19,
    gesamtBrutto: 200.00,
    bezahltAm: "2025-10-14",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-10-15",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-10-16",
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-10-14",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "31-0",
    kaufdatum: "2025-10-20",
    bestellnummer: "7384756293",
    info: "Eilauftrag",
    kundeAdresse: "Thomas Becker, Hauptstr. 78, 20095 Hamburg",
    email: "thomas.becker@example.com",
    telefonnummer: "+49 40 45678901",
    artikelanzahl: 4,
    gesamtNetto: 252.10,
    mwstSatz: 19,
    gesamtBrutto: 300.00,
    bezahltAm: "2025-10-20",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton XL",
    versandtGemeldet: "2025-10-21",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-10-22",
    versandBrutto: 7.99,
    versandNetto: 6.71,
    importdatum: "2025-10-20",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "32-0",
    kaufdatum: "2025-10-26",
    bestellnummer: "8475629384",
    info: "",
    kundeAdresse: "Petra Schulz, Bahnhofstr. 67, 80331 München",
    email: "petra.schulz@example.com",
    telefonnummer: "+49 89 56789012",
    artikelanzahl: 2,
    gesamtNetto: 126.05,
    mwstSatz: 19,
    gesamtBrutto: 150.00,
    bezahltAm: "2025-10-26",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "UPS",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-10-27",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-10-28",
    versandBrutto: 5.49,
    versandNetto: 4.61,
    importdatum: "2025-10-26",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  // Additional Sendungen entries
  {
    nr: "33-0",
    kaufdatum: "2025-07-15",
    bestellnummer: "1928374650",
    info: "Express",
    kundeAdresse: "Andreas Müller, Friedrichstr. 45, 10117 Berlin",
    email: "andreas.mueller@example.com",
    telefonnummer: "+49 30 11111111",
    artikelanzahl: 2,
    gesamtNetto: 84.03,
    mwstSatz: 19,
    gesamtBrutto: 100.00,
    bezahltAm: "2025-07-15",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-07-16",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-07-17",
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-07-15",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "34-0",
    kaufdatum: "2025-07-22",
    bestellnummer: "2837465921",
    info: "",
    kundeAdresse: "Claudia Weber, Mönckebergstr. 12, 20095 Hamburg",
    email: "claudia.weber@example.com",
    telefonnummer: "+49 40 22222222",
    artikelanzahl: 1,
    gesamtNetto: 42.02,
    mwstSatz: 19,
    gesamtBrutto: 50.00,
    bezahltAm: "2025-07-22",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "Hermes",
    versandverpackung: "Karton S",
    versandtGemeldet: "2025-07-23",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-07-24",
    versandBrutto: 4.99,
    versandNetto: 4.19,
    importdatum: "2025-07-22",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "35-0",
    kaufdatum: "2025-08-01",
    bestellnummer: "3746592837",
    info: "Geschenkverpackung",
    kundeAdresse: "Stefan Fischer, Marienplatz 8, 80331 München",
    email: "stefan.fischer@example.com",
    telefonnummer: "+49 89 33333333",
    artikelanzahl: 3,
    gesamtNetto: 168.07,
    mwstSatz: 19,
    gesamtBrutto: 200.00,
    bezahltAm: "2025-08-01",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton L",
    versandtGemeldet: "2025-08-02",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-08-03",
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-08-01",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "36-0",
    kaufdatum: "2025-09-01",
    bestellnummer: "4659283746",
    info: "Eilauftrag",
    kundeAdresse: "Nina Schneider, Schadowstr. 23, 40212 Düsseldorf",
    email: "nina.schneider@example.com",
    telefonnummer: "+49 211 44444444",
    artikelanzahl: 4,
    gesamtNetto: 252.10,
    mwstSatz: 19,
    gesamtBrutto: 300.00,
    bezahltAm: "2025-09-01",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton XL",
    versandtGemeldet: "2025-09-02",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-09-03",
    versandBrutto: 7.99,
    versandNetto: 6.71,
    importdatum: "2025-09-01",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "37-0",
    kaufdatum: "2025-09-30",
    bestellnummer: "5928374659",
    info: "",
    kundeAdresse: "Oliver Wagner, Zeil 89, 60313 Frankfurt",
    email: "oliver.wagner@example.com",
    telefonnummer: "+49 69 55555555",
    artikelanzahl: 2,
    gesamtNetto: 105.04,
    mwstSatz: 19,
    gesamtBrutto: 125.00,
    bezahltAm: "2025-09-30",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "UPS",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-10-01",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-10-02",
    versandBrutto: 5.49,
    versandNetto: 4.61,
    importdatum: "2025-09-30",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "38-0",
    kaufdatum: "2025-10-31",
    bestellnummer: "6283746592",
    info: "Express",
    kundeAdresse: "Lisa Hoffmann, Hauptstr. 56, 70173 Stuttgart",
    email: "lisa.hoffmann@example.com",
    telefonnummer: "+49 711 66666666",
    artikelanzahl: 1,
    gesamtNetto: 84.03,
    mwstSatz: 19,
    gesamtBrutto: 100.00,
    bezahltAm: "2025-10-31",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton S",
    versandtGemeldet: "2025-11-01",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-11-02",
    versandBrutto: 4.99,
    versandNetto: 4.19,
    importdatum: "2025-10-31",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "39-0",
    kaufdatum: "2025-11-05",
    bestellnummer: "7384659283",
    info: "",
    kundeAdresse: "Marco Schmidt, Königsallee 34, 40212 Düsseldorf",
    email: "marco.schmidt@example.com",
    telefonnummer: "+49 211 77777777",
    artikelanzahl: 5,
    gesamtNetto: 294.12,
    mwstSatz: 19,
    gesamtBrutto: 350.00,
    bezahltAm: "2025-11-05",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton L",
    versandtGemeldet: "2025-11-06",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-11-07",
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-11-05",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "40-0",
    kaufdatum: "2025-11-12",
    bestellnummer: "8475928374",
    info: "Retourenfall",
    kundeAdresse: "Sandra Becker, Schillerstr. 67, 20095 Hamburg",
    email: "sandra.becker@example.com",
    telefonnummer: "+49 40 88888888",
    artikelanzahl: 3,
    gesamtNetto: 168.07,
    mwstSatz: 19,
    gesamtBrutto: 200.00,
    bezahltAm: "2025-11-12",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "Hermes",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-11-13",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-11-14",
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-11-12",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "41-0",
    kaufdatum: "2025-11-18",
    bestellnummer: "9562837465",
    info: "",
    kundeAdresse: "Thomas Klein, Maximilianstr. 45, 80539 München",
    email: "thomas.klein@example.com",
    telefonnummer: "+49 89 99999999",
    artikelanzahl: 2,
    gesamtNetto: 126.05,
    mwstSatz: 19,
    gesamtBrutto: 150.00,
    bezahltAm: "2025-11-18",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-11-19",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-11-20",
    versandBrutto: 5.49,
    versandNetto: 4.61,
    importdatum: "2025-11-18",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "42-0",
    kaufdatum: "2025-11-25",
    bestellnummer: "1629384756",
    info: "Express",
    kundeAdresse: "Julia Müller, Rheinstr. 78, 50667 Köln",
    email: "julia.mueller@example.com",
    telefonnummer: "+49 221 10101010",
    artikelanzahl: 4,
    gesamtNetto: 252.10,
    mwstSatz: 19,
    gesamtBrutto: 300.00,
    bezahltAm: "2025-11-25",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "UPS",
    versandverpackung: "Karton XL",
    versandtGemeldet: "2025-11-26",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-11-27",
    versandBrutto: 7.99,
    versandNetto: 6.71,
    importdatum: "2025-11-25",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "43-0",
    kaufdatum: "2025-12-01",
    bestellnummer: "2738495061",
    info: "",
    kundeAdresse: "Michael Schulz, Bahnhofstr. 34, 60313 Frankfurt",
    email: "michael.schulz@example.com",
    telefonnummer: "+49 69 20202020",
    artikelanzahl: 1,
    gesamtNetto: 42.02,
    mwstSatz: 19,
    gesamtBrutto: 50.00,
    bezahltAm: "2025-12-01",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "Hermes",
    versandverpackung: "Karton S",
    versandtGemeldet: "2025-12-02",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-12-03",
    versandBrutto: 4.99,
    versandNetto: 4.19,
    importdatum: "2025-12-01",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "44-0",
    kaufdatum: "2025-12-05",
    bestellnummer: "3849506172",
    info: "Geschenkverpackung",
    kundeAdresse: "Anna Fischer, Hohe Str. 12, 20095 Hamburg",
    email: "anna.fischer@example.com",
    telefonnummer: "+49 40 30303030",
    artikelanzahl: 3,
    gesamtNetto: 168.07,
    mwstSatz: 19,
    gesamtBrutto: 200.00,
    bezahltAm: "2025-12-05",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton L",
    versandtGemeldet: "2025-12-06",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-12-07",
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-12-05",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
  {
    nr: "45-0",
    kaufdatum: "2025-12-10",
    bestellnummer: "4950617283",
    info: "Eilauftrag",
    kundeAdresse: "Peter Weber, Marienplatz 23, 80331 München",
    email: "peter.weber@example.com",
    telefonnummer: "+49 89 40404040",
    artikelanzahl: 5,
    gesamtNetto: 210.08,
    mwstSatz: 19,
    gesamtBrutto: 250.00,
    bezahltAm: "2025-12-10",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton XL",
    versandtGemeldet: "2025-12-11",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-12-12",
    versandBrutto: 7.99,
    versandNetto: 6.71,
    importdatum: "2025-12-10",
    importquelle: "Amazon API",
    type: "Versandvorgang",
  },
];

// Additional rows for table 1 only
const table1AdditionalRows: Order[] = [
  {
    nr: 17,
    kaufdatum: "2025-11-12",
    bestellnummer: "2938475612",
    info: "Express",
    kundeAdresse: "Lisa Wagner, Königsallee 33, 40212 Düsseldorf",
    email: "lisa.wagner@example.com",
    telefonnummer: "+49 211 67890123",
    artikelanzahl: 2,
    gesamtNetto: 168.07,
    mwstSatz: 19,
    gesamtBrutto: 200.00,
    bezahltAm: "2025-11-13",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "DHL",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-11-13",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-11-14",
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-11-12",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 18,
    kaufdatum: "2025-11-15",
    bestellnummer: "7482936150",
    info: "",
    kundeAdresse: "Michael Koch, Hauptbahnhofstr. 5, 70173 Stuttgart",
    email: "michael.koch@example.com",
    telefonnummer: "+49 711 78901234",
    artikelanzahl: 4,
    gesamtNetto: 252.10,
    mwstSatz: 19,
    gesamtBrutto: 300.00,
    bezahltAm: null,
    statusRechnungsversand: "ausstehend",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton L",
    versandtGemeldet: null,
    statusVersanddokumente: "ausstehend",
    versanddatum: null,
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-11-15",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  // August rows (3 rows)
  {
    nr: 1,
    kaufdatum: "2025-08-15",
    bestellnummer: "8472936151",
    info: "",
    kundeAdresse: "Sarah Klein, Musterstr. 10, 10115 Berlin",
    email: "sarah.klein@example.com",
    telefonnummer: "+49 30 11111111",
    artikelanzahl: 2,
    gesamtNetto: 84.03,
    mwstSatz: 19,
    gesamtBrutto: 100.00,
    bezahltAm: "2025-08-16",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-08-16",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-08-17",
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-08-15",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 2,
    kaufdatum: "2025-08-20",
    bestellnummer: "2938475613",
    info: "Express",
    kundeAdresse: "Thomas Müller, Hauptstr. 5, 20095 Hamburg",
    email: "thomas.mueller@example.com",
    telefonnummer: "+49 40 22222222",
    artikelanzahl: 3,
    gesamtNetto: 126.05,
    mwstSatz: 19,
    gesamtBrutto: 150.00,
    bezahltAm: "2025-08-21",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton L",
    versandtGemeldet: "2025-08-21",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-08-22",
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-08-20",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 3,
    kaufdatum: "2025-08-25",
    bestellnummer: "7482936151",
    info: "",
    kundeAdresse: "Julia Schmidt, Marktplatz 12, 80331 München",
    email: "julia.schmidt@example.com",
    telefonnummer: "+49 89 33333333",
    artikelanzahl: 1,
    gesamtNetto: 42.02,
    mwstSatz: 19,
    gesamtBrutto: 50.00,
    bezahltAm: null,
    statusRechnungsversand: "ausstehend",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "Hermes",
    versandverpackung: "Karton S",
    versandtGemeldet: null,
    statusVersanddokumente: "ausstehend",
    versanddatum: null,
    versandBrutto: 4.99,
    versandNetto: 4.19,
    importdatum: "2025-08-25",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  // September rows (6 rows)
  {
    nr: 4,
    kaufdatum: "2025-09-01",
    bestellnummer: "6193847252",
    info: "",
    kundeAdresse: "Markus Weber, Rheinstr. 8, 50667 Köln",
    email: "markus.weber@example.com",
    telefonnummer: "+49 221 44444444",
    artikelanzahl: 4,
    gesamtNetto: 168.07,
    mwstSatz: 19,
    gesamtBrutto: 200.00,
    bezahltAm: "2025-09-02",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-09-02",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-09-03",
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-09-01",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 5,
    kaufdatum: "2025-09-05",
    bestellnummer: "2938475614",
    info: "Geschenkverpackung",
    kundeAdresse: "Nicole Fischer, Schillerstr. 20, 60313 Frankfurt",
    email: "nicole.fischer@example.com",
    telefonnummer: "+49 69 55555555",
    artikelanzahl: 2,
    gesamtNetto: 84.03,
    mwstSatz: 19,
    gesamtBrutto: 100.00,
    bezahltAm: "2025-09-06",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-09-06",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-09-07",
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-09-05",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 6,
    kaufdatum: "2025-09-10",
    bestellnummer: "8472936152",
    info: "",
    kundeAdresse: "Daniel Bauer, Königsallee 15, 40212 Düsseldorf",
    email: "daniel.bauer@example.com",
    telefonnummer: "+49 211 66666666",
    artikelanzahl: 5,
    gesamtNetto: 210.08,
    mwstSatz: 19,
    gesamtBrutto: 250.00,
    bezahltAm: null,
    statusRechnungsversand: "ausstehend",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton L",
    versandtGemeldet: null,
    statusVersanddokumente: "ausstehend",
    versanddatum: null,
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-09-10",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 7,
    kaufdatum: "2025-09-15",
    bestellnummer: "1847293652",
    info: "Eilauftrag",
    kundeAdresse: "Stephanie Wagner, Hauptbahnhofstr. 8, 70173 Stuttgart",
    email: "stephanie.wagner@example.com",
    telefonnummer: "+49 711 77777777",
    artikelanzahl: 3,
    gesamtNetto: 126.05,
    mwstSatz: 19,
    gesamtBrutto: 150.00,
    bezahltAm: "2025-09-16",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "UPS",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-09-16",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-09-17",
    versandBrutto: 5.49,
    versandNetto: 4.61,
    importdatum: "2025-09-15",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 8,
    kaufdatum: "2025-09-20",
    bestellnummer: "3958274613",
    info: "",
    kundeAdresse: "Andreas Koch, Berliner Str. 30, 20095 Hamburg",
    email: "andreas.koch@example.com",
    telefonnummer: "+49 40 88888888",
    artikelanzahl: 1,
    gesamtNetto: 42.02,
    mwstSatz: 19,
    gesamtBrutto: 50.00,
    bezahltAm: "2025-09-21",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "Hermes",
    versandverpackung: "Karton S",
    versandtGemeldet: "2025-09-21",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-09-22",
    versandBrutto: 4.99,
    versandNetto: 4.19,
    importdatum: "2025-09-20",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 9,
    kaufdatum: "2025-09-25",
    bestellnummer: "7293846151",
    info: "",
    kundeAdresse: "Christina Meyer, Marktplatz 3, 80331 München",
    email: "christina.meyer@example.com",
    telefonnummer: "+49 89 99999999",
    artikelanzahl: 4,
    gesamtNetto: 168.07,
    mwstSatz: 19,
    gesamtBrutto: 200.00,
    bezahltAm: null,
    statusRechnungsversand: "ausstehend",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton M",
    versandtGemeldet: null,
    statusVersanddokumente: "ausstehend",
    versanddatum: null,
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-09-25",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  // October rows (4 rows)
  {
    nr: 10,
    kaufdatum: "2025-10-01",
    bestellnummer: "2938475615",
    info: "",
    kundeAdresse: "Martin Schulz, Hauptstr. 25, 10115 Berlin",
    email: "martin.schulz@example.com",
    telefonnummer: "+49 30 10101010",
    artikelanzahl: 2,
    gesamtNetto: 84.03,
    mwstSatz: 19,
    gesamtBrutto: 100.00,
    bezahltAm: "2025-10-02",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-10-02",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-10-03",
    versandBrutto: 5.99,
    versandNetto: 5.03,
    importdatum: "2025-10-01",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 11,
    kaufdatum: "2025-10-05",
    bestellnummer: "7482936152",
    info: "Express",
    kundeAdresse: "Laura Hoffmann, Rheinstr. 18, 50667 Köln",
    email: "laura.hoffmann@example.com",
    telefonnummer: "+49 221 20202020",
    artikelanzahl: 3,
    gesamtNetto: 126.05,
    mwstSatz: 19,
    gesamtBrutto: 150.00,
    bezahltAm: "2025-10-06",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "DPD International",
    versanddienstleister: "DPD",
    versandverpackung: "Karton M",
    versandtGemeldet: "2025-10-06",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-10-07",
    versandBrutto: 5.49,
    versandNetto: 4.61,
    importdatum: "2025-10-05",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 12,
    kaufdatum: "2025-10-10",
    bestellnummer: "6193847253",
    info: "",
    kundeAdresse: "Sebastian Richter, Schillerstr. 25, 60313 Frankfurt",
    email: "sebastian.richter@example.com",
    telefonnummer: "+49 69 30303030",
    artikelanzahl: 5,
    gesamtNetto: 210.08,
    mwstSatz: 19,
    gesamtBrutto: 250.00,
    bezahltAm: null,
    statusRechnungsversand: "ausstehend",
    versandland: "DE",
    versandprofil: "DHL National",
    versanddienstleister: "DHL",
    versandverpackung: "Karton L",
    versandtGemeldet: null,
    statusVersanddokumente: "ausstehend",
    versanddatum: null,
    versandBrutto: 6.99,
    versandNetto: 5.87,
    importdatum: "2025-10-10",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
  {
    nr: 13,
    kaufdatum: "2025-10-15",
    bestellnummer: "8472936153",
    info: "",
    kundeAdresse: "Melanie Zimmermann, Königsallee 22, 40212 Düsseldorf",
    email: "melanie.zimmermann@example.com",
    telefonnummer: "+49 211 40404040",
    artikelanzahl: 1,
    gesamtNetto: 42.02,
    mwstSatz: 19,
    gesamtBrutto: 50.00,
    bezahltAm: "2025-10-16",
    statusRechnungsversand: "versendet",
    versandland: "DE",
    versandprofil: "–",
    versanddienstleister: "Hermes",
    versandverpackung: "Karton S",
    versandtGemeldet: "2025-10-16",
    statusVersanddokumente: "erstellt",
    versanddatum: "2025-10-17",
    versandBrutto: 4.99,
    versandNetto: 4.19,
    importdatum: "2025-10-15",
    importquelle: "Amazon API",
    type: "Bestellung",
  },
];


function DashboardPage() {
  // Separate data sources for each table
  const [ordersState1] = React.useState<Order[]>([...orders, ...table1AdditionalRows]);
  const [ordersState2] = React.useState<Order[]>(orders);
  const [selectedPeriod, setSelectedPeriod] = React.useState<string>("Jahr");

  // Prepare chart data - aggregate by month
  const chartData = React.useMemo(() => {
    // Get current year
    const currentYear = new Date().getFullYear();
    
    // Initialize all 12 months with 0 counts
    const months = [
      "Jan", "Feb", "Mär", "Apr", "Mai", "Jun",
      "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"
    ];
    
    const monthlyData = months.map((month) => ({
      month,
      bestellung: 0,
      versandvorgang: 0,
    }));

    // Filter table 1 (Bestellung)
    const table1Data = [...ordersState1].filter(order => order.type === "Bestellung");
    // Filter table 2 (Versandvorgang)
    const table2Data = [...ordersState2].filter(order => order.type === "Versandvorgang");

    // Count by month for table 1
    table1Data.forEach(order => {
      const date = new Date(order.importdatum);
      if (date.getFullYear() === currentYear) {
        const monthIndex = date.getMonth();
        monthlyData[monthIndex].bestellung++;
      }
    });

    // Count by month for table 2 (Sendungen) - use versanddatum instead of importdatum
    table2Data.forEach(order => {
      // Use versanddatum for Versandvorgang entries, fallback to importdatum if versanddatum is null
      const dateString = order.versanddatum || order.importdatum;
      if (dateString) {
        const date = new Date(dateString);
        if (date.getFullYear() === currentYear) {
          const monthIndex = date.getMonth();
          monthlyData[monthIndex].versandvorgang++;
        }
      }
    });

    return monthlyData;
  }, [ordersState1, ordersState2]);

  const chartConfig = {
    bestellung: {
      label: "Bestellungen",
      color: "var(--primary)",
    },
    versandvorgang: {
      label: "Sendungen",
      color: "#72CFF6",
    },
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto">
        <div className="flex flex-col lg:flex-row items-stretch">
          {/* Menu - horizontal on small screens, vertical on large screens */}
          <div className="w-[calc(100%-40px)] lg:w-[56px] h-auto lg:h-[calc(100vh-40px)] mt-5 lg:mt-[20px] lg:sticky lg:top-[20px] pl-4 pr-1 py-1 lg:pl-2 lg:pr-2 lg:py-4 bg-primary mx-5 lg:ml-5 lg:mr-2 rounded-[12px] flex-shrink-0 flex flex-row lg:flex-col items-center justify-between lg:justify-start gap-2 lg:gap-4 mb-2 lg:mb-0" data-name="Menu">
            <Link to="/versions" className="w-fit lg:w-full flex items-center justify-center">
              <img src={logoPlus} alt="Logo" className="w-[90px] h-auto lg:hidden brightness-0 invert" />
              <img src={logo} alt="Logo" className="hidden lg:block w-[90%] h-auto brightness-0 invert" />
            </Link>
            {/* Burger menu button for small screens */}
            <button className="lg:hidden flex items-center justify-center w-10 h-10 rounded-md bg-transparent hover:bg-white/15 transition-colors">
              <Menu className="size-5 text-white" />
            </button>
            {/* Original buttons for large screens */}
            <div className="hidden lg:flex flex-col gap-0.5 w-full mt-4">
              <Link to="/1.2/dashboard" className="flex items-center justify-center w-full aspect-square rounded-md bg-white transition-colors">
                <LayoutDashboard className="size-5 text-foreground" />
              </Link>
              <Link to="/1.2/shipping" className="flex items-center justify-center w-full aspect-square rounded-md hover:bg-white/15 transition-colors">
                <Truck className="size-5 text-white" />
              </Link>
              <Link to="/1.2/tools" className="flex items-center justify-center w-full aspect-square rounded-md hover:bg-white/15 transition-colors">
                <ToyBrick className="size-5 text-white" />
              </Link>
              <Link to="/1.2/settings" className="flex items-center justify-center w-full aspect-square rounded-md hover:bg-white/15 transition-colors">
                <Settings className="size-5 text-white" />
              </Link>
              <div className="flex items-center justify-center w-full aspect-square rounded-md hover:bg-white/15 transition-colors">
                <HelpCircle className="size-5 text-white" />
              </div>
            </div>
            {/* Version number at bottom */}
            <div className="hidden lg:block mt-auto pt-4">
              <div className="text-white/70 text-xs text-center font-medium">
                v1.2
              </div>
            </div>
          </div>

          {/* Right part - flexible width */}
          <div className="flex-1 min-w-0 px-6 py-5 lg:px-8 lg:py-10 flex flex-col gap-[28px]">
            <div className="flex flex-col gap-0.5">
              <div className="text-sm text-foreground">
                {format(new Date(), "EEEE, dd.MM.yyyy", { locale: de })}
              </div>
              <h1>
                Willkommen Thomas
              </h1>
            </div>
            
            {/* Chart */}
            <Card className="w-full h-[35vh] flex flex-col shadow-none">
              <CardHeader className="flex flex-row items-center justify-between">
                <h2>Versand</h2>
                <Select value={selectedPeriod} onValueChange={setSelectedPeriod}>
                  <SelectTrigger className="w-[120px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Jahr">Jahr</SelectItem>
                    <SelectItem value="Monat">Monat</SelectItem>
                    <SelectItem value="Woche">Woche</SelectItem>
                  </SelectContent>
                </Select>
              </CardHeader>
              <CardContent className="flex-1 overflow-hidden">
                <ChartContainer config={chartConfig} className="h-full w-full">
                  <BarChart data={chartData} margin={{ left: -20, right: 0, top: 0, bottom: 0 }}>
                    <CartesianGrid vertical={false} />
                    <XAxis 
                      dataKey="month" 
                      tickLine={false} 
                      tickMargin={10} 
                      axisLine={false}
                      tick={{ fill: "hsl(var(--muted-foreground))" }}
                    />
                    <YAxis 
                      tickLine={false} 
                      axisLine={false}
                      tick={{ fill: "hsl(var(--muted-foreground))" }}
                    />
                    <Tooltip content={<ChartTooltipContent />} />
                    <Bar 
                      dataKey="bestellung" 
                      fill="var(--primary)" 
                      radius={4}
                      name="Bestellungen"
                    />
                    <Bar 
                      dataKey="versandvorgang" 
                      fill="#72CFF6" 
                      radius={4}
                      name="Sendungen"
                    />
                  </BarChart>
                </ChartContainer>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>

    </div>
  );
}

export default DashboardPage;
